version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_api_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chimera_db
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    expose:
      - 5432:5432
    networks:
      - api-service

  api-service:
    build:
      dockerfile: Dockerfile
    container_name: api-service
    expose:
      - 8080:8080
    networks:
      - api-service

networks:
  api-service:

volumes:
  postgres_data1:
