DROP TABLE IF EXISTS RELATIONAL_EXTRACT_METADATA_CONFIG CASCADE;
CREATE TABLE IF NOT EXISTS RELATIONAL_EXTRACT_METADATA_CONFIG (
  DATABASE_NAME               VARCHAR(255),
  TABLE_NAME                  VARCHAR(255),
  SCHEMA_NAME                 VARCHAR(255),
  SQL_TEXT                    TEXT,
 -- DATA_SOURCE_CONNECTION_NAME VARCHAR(255),
  CONSTRAINT fk_data_source_connection FOREIGN KEY (DATA_SOURCE_CONNECTION_NAME) REFERENCES DATA_SOURCES_CONNECTIONS(DATA_SOURCE_CONNECTION_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pipeline_name FOREIGN KEY (PIPELINE_NAME) REFERENCES DATA_PIPELINES(PIPELINE_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_data_source FOREIGN KEY (EXTRACT_SOURCE_TYPE, EXTRACT_SOURCE_SUB_TYPE) REFERENCES DATA_SOURCES(DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_pipeline_name_sequence_number UNIQUE (PIPELINE_NAME, SEQUENCE_NUMBER)
  ) INHERITS (EXTRACT_METADATA_CONFIG);


  INSERT INTO RELATIONAL_EXTRACT_METADATA_CONFIG (PIPELINE_NAME, SEQUENCE_NUMBER, EXTRACT_SOURCE_TYPE, EXTRACT_SOURCE_SUB_TYPE, PREDECESSOR_SEQUENCES, SUCCESSOR_SEQUENCES, DATABASE_NAME, TABLE_NAME, SCHEMA_NAME, SQL_TEXT, data_source_connection_name, source_configuration, DATAFRAME_NAME, ROW_FILTER, COLUMN_FILTER, CREATED_BY, UPDATED_BY) VALUES 
('Test_Pipeline', 3, 'Relational', 'Postgres', '2', '4', 'chimera_db', 'data_sources', null, null,'Chimera_Postgres_Local_connection', null, 'DF_postgres', null, null, 'PK', 'null, null');


select * from relational_extract_metadata_config;