DROP TABLE IF EXISTS DATA_SOURCES_CONNECTIONS;

CREATE TABLE DATA_SOURCES_CONNECTIONS (
    DATA_SOURCE_CONNECTION_NAME         VARCHAR(255) NOT NULL,
	DATA_SOURCE_TYPE        VARCHAR(255),
    DATA_SOURCE_SUB_TYPE    VARCHAR(255),
    AUTHENTICATION_TYPE     VARCHAR(50) NOT NULL CHECK (AUTHENTICATION_TYPE IN ('AWS_SECRET', 'GCP_SECRET', 'AZURE_SECRET', 'USER_PASSWORD')),
    AUTHENTICATION_DATA     TEXT NOT NULL,
	CONNECTION_METADATA     TEXT,
	USER_READ_CONFIG        TEXT,
	USER_WRITE_CONFIG       TEXT,
    DESCRIPTION             TEXT NOT NULL,
    CREATED_TIMESTAMP       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY              VARCHAR(255) DEFAULT CURRENT_USER,
    UPDATED_TIMESTAMP       TIMESTAMP,
    UPDATED_BY              VARCHAR(255),
    ACTIVE_FLAG             VARCHAR(1) DEFAULT 'Y' :: CHARACTER VARYING,
    CONSTRAINT check_data_sources_connections_active_flag CHECK (ACTIVE_FLAG in ('Y', 'N')),
    CONSTRAINT pk_data_sources_connections PRIMARY KEY (DATA_SOURCE_CONNECTION_NAME),
    CONSTRAINT fk_data_sources_connections_data_sources FOREIGN KEY (DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) REFERENCES DATA_SOURCES (DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) ON DELETE CASCADE
);


INSERT INTO DATA_SOURCES_CONNECTIONS (DATA_SOURCE_CONNECTION_NAME, DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE, AUTHENTICATION_TYPE, AUTHENTICATION_DATA, CONNECTION_METADATA, USER_READ_CONFIG, USER_WRITE_CONFIG, DESCRIPTION, CREATED_BY, UPDATED_TIMESTAMP, UPDATED_BY)
VALUES ('Chimera_Postgres_Local_connection', 'Relational', 'Postgres', 'USER_PASSWORD', '{"username":"chimera","password":"chimera123"}', 'jdbc:postgresql://localhost:5432/chimera_db', null, null, 'Connectiona details of chimera_db installed locally on postgres', 'PK', NULL, NULL);

select * from data_sources_connections;