CREATE TABLE IF NOT EXISTS NOSQL_PERSIST_METADATA_CONFIG (
  COLLECTION                    VARCHAR(4000),
  PARTITIONER                   VARCHAR(255),
  CONSTRAINT fk_data_source_connection FOREIGN KEY (DATA_SOURCE_CONNECTION_NAME) REFERENCES DATA_SOURCES_CONNECTIONS(DATA_SOURCE_CONNECTION_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pipeline_name FOREIGN KEY (PIPELINE_NAME) REFERENCES DATA_PIPELINES(PIPELINE_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_data_source FOREIGN KEY (SINK_TYPE, SINK_SUB_TYPE) REFERENCES DATA_SOURCES(DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_pipeline_name_sequence_number_nosql_persist UNIQUE (PIPELINE_NAME, SEQUENCE_NUMBER)
  ) INHERITS (PERSIST_METADATA_CONFIG);