CREATE TABLE IF NOT EXISTS FILE_PERSIST_METADATA_CONFIG (
  FILE_NAME              VARCHAR(255),
  FILE_PATH              VARCHAR(4000),
  WRITE_MODE		VARCHAR(255) CHECK (WRITE_MODE IN ('OVERWRITE', 'APPEND')),
  CONSTRAINT fk_pipeline_name FOREIGN KEY (PIPELINE_NAME) REFERENCES DATA_PIPELINES(PIPELINE_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_data_source FOREIGN KEY (SINK_TYPE, SINK_SUB_TYPE) REFERENCES DATA_SOURCES(DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_pipeline_name_sequence_number_file_persist UNIQUE (PIPELINE_NAME, SEQUENCE_NUMBER)
  ) INHERITS (PERSIST_METADATA_CONFIG);