-- Active: 1736164021460@@localhost@5432@chimera_db
-- Active: 1736164021460@@localhost@5432@postgres@public
ALTER TABLE PERSIST_METADATA_CONFIG
    ADD COLUMN PREDECESSOR_SEQUENCES 	VARCHAR(100),
    ADD COLUMN SUCCESSOR_SEQUENCES 		VARCHAR(100),
    DROP COLUMN DATABASE_NAME,
    DROP COLUMN SCHEMA_NAME,
    DROP COLUMN TABLE_NAME,
    DROP COLUMN TARGET_PATH,
    DROP COLUMN WRITE_MODE,
    DROP COLUMN KAFKA_TOPIC,
    DROP COLUMN KAFKA_KEY,
    DROP COLUMN KAFKA_MESSAGE;