  CREATE TABLE IF NOT EXISTS STREAMS_PERSIST_METADATA_CONFIG (
  KAFKA_TOPIC          VARCHAR(1000),
  KAFKA_KEY                   TEXT,
  KAFKA_MESSAGE               TEXT,
  
  CONSTRAINT fk_data_source_connection FOREIGN KEY (DATA_SOURCE_CONNECTION_NAME) REFERENCES DATA_SOURCES_CONNECTIONS(DATA_SOURCE_CONNECTION_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pipeline_name FOREIGN KEY (PIPELINE_NAME) REFERENCES DATA_PIPELINES(PIPELINE_NAME) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_data_source FOREIGN KEY (SINK_TYPE, SINK_SUB_TYPE) REFERENCES DATA_SOURCES(DATA_SOURCE_TYPE, DATA_SOURCE_SUB_TYPE) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uq_pipeline_name_sequence_number_stream_persist UNIQUE (PIPELINE_NAME, SEQUENCE_NUMBER)
  ) INHERITS (PERSIST_METADATA_CONFIG);
