server:
  port: 8080
spring:
  application:
    name: chimera_api_service_dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=data_pipeline # PostgreSQL for default environment
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      poolName: PostgresqlHikariCP
      maxLifetime: 1200000 # 20 minutes
      maximumPoolSize: 10 # Maximum connections in the pool
      minimumIdle: 1 # Minimum idle connections in the pool
  flyway:
    enabled: true
    schemas: data_pipeline
    cleanDisabled: true

mybatis:
  type-aliases-package: org.pantherslabs.chimera.unisca.pipeline_metadata_api.entity
  type-handlers-package: com.progressive.minds.chimera.configuration.handler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

management:
  health:
    consul:
      enabled: false
  server:
    servlet:
      context-path: /actuator  # Custom path for Actuator endpoints
  endpoints:
    web:
      exposure:
        include: health, info  # Expose health and info endpoints

security:
  userName: chimera # Username for private endpoint access
  password: password # Password for private endpoint access

resilience4j.circuitbreaker:
  instances:
    externalService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.ratelimiter:
  instances:
    externalService:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

