server:
  port: 8080
spring:
  application:
    name: chimera_api_service_local
  datasource:
    url: jdbc:postgresql://localhost:15432/chimera_db_test #?currentSchema=data_pipeline # PostgreSQL for default environment
    driverClassName: org.postgresql.Driver
    username: chimera_user
    password: chimera_pass
    hikari:
      poolName: PostgresqlHikariCP
      maxLifetime: 1200000 # 20 minutes
      maximumPoolSize: 10 # Maximum connections in the pool
      minimumIdle: 1 # Minimum idle connections in the pool
  flyway:
    enabled: false
    schemas: data_pipeline
    cleanDisabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: chimera_api_client
          #          issuer-uri: http://localhost:3000/realms/chimera-api-service-realm
          issuer-uri: "https://deviam.pantherslabs.com/realms/chimera"
          #          issuer-uri: "http://localhost:8800/realms/chimera_api"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

mybatis:
  type-aliases-package: org.pantherslabs.chimera.unisca.pipeline_metadata_api.entity
  type-handlers-package: com.progressive.minds.chimera.configuration.handler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

management:
  server:
    servlet:
      context-path: /actuator  # Correct management context path
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j.circuitbreaker:
  instances:
    externalService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.ratelimiter:
  instances:
    externalService:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100