name: Unisca Build Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Step 2 - Extract or Set Version
        id: extract_version
        run: |
          set -euo pipefail

          pom_version=$(grep -m 1 '<version>' pom.xml | sed -E 's/.*<version>(.+)<\/version>.*/\1/')
          version_input="${{ github.event.inputs.version }}"

          # Use version from input or fallback to POM
          version="${version_input:-$pom_version}"
          echo "Using Version: $version"
          echo "version=${version,,}" >> "$GITHUB_OUTPUT"

      - name: Step 3 - Import GPG Key
        run: |
          echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import
          echo "${{ secrets.GPG_SECRET_KEY }}" | gpg --import --no-tty --batch --yes

      - name: Step 4 - Set up Java & Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Step 5 - Set Maven Project Version
        run: mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.version }}

      - name: Step 6 - Build JARs
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean install -DskipTests --batch-mode

      - name: Step 7 - Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Step 8 - Build and Push Docker Images
        run: |
          set -euo pipefail
          version="${{ steps.extract_version.outputs.version }}"

          for jar in $(find . -name "*.jar" -not -path "*/target/original-*.jar"); do
            module_dir=$(dirname "$jar")
            module_dir="${module_dir%/target}"
            module_name=$(basename "$module_dir")

            formatted_module_name=$(echo "$module_name" | tr '[:upper:]' '[:lower:]' | tr -s '[:space:]' '_' | sed 's/__/_/g' | sed 's/_$//')
            image_name="pantherslabspvtltd/${formatted_module_name}:${version}"

            echo "Processing $jar -> $image_name"

            # Ensure Dockerfile exists
            if [ ! -f "$module_dir/Dockerfile" ]; then
              echo "Creating Dockerfile in $module_dir"
              cat <<EOF > "$module_dir/Dockerfile"
              FROM eclipse-temurin:17-jre
              COPY $(basename "$jar") /app.jar
              ENTRYPOINT ["java", "-jar", "/app.jar"]
              EOF
            fi

            # Ensure the JAR is in the right location
            dest_jar="$module_dir/$(basename "$jar")"
            if [ "$jar" != "$dest_jar" ]; then
              cp "$jar" "$dest_jar"
            fi

            echo "Building Docker image: $image_name"
            docker build -t "$image_name" "$module_dir"
            docker push "$image_name"
          done
